name: Build docker file
on:
  push:
    branches:
      - docker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t image_latest
